### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by Nurikan-sketch** [vypivshiy/ani-cli-ru#19]
Defaulting to user installation because normal site-packages is not writeable
Processing /home/nurikan/ani-cli-ru
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-e6oyrf85/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-e6oyrf85/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-e6oyrf85/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-e6oyrf85/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/home/nurikan/ani-cli-ru/anicli_ru/__init__.py", line 1, in <module>
          from anicli_ru.kodik import Kodik
        File "/home/nurikan/ani-cli-ru/anicli_ru/kodik.py", line 8, in <module>
          from anicli_ru._http import client
        File "/home/nurikan/ani-cli-ru/anicli_ru/_http.py", line 4, in <module>
          from requests import Session, Response
      ModuleNotFoundError: No module named 'requests'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Установка requests не помогла

**Comment by vasilyvaganov** [comment]
I don't know if this helps anyone, but for me, installing "wheel" fixed the problem.
Не знаю, поможет ли это кому-то, но у меня эту проблему исправила установка "wheel"
`pip3 install requests wheel`

**Comment by Nurikan-sketch** [comment]
Помогло обновление python до 3.10.10
Updating python to 3.10.10 helped
