### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by Ziquiet** [vypivshiy/ani-cli-ru#2]
$ anicli-ru

$ h

$ o

$ Results not founded!
Choose anime: 1 - 0
c_o [1-0] > 
Results not founded!
Choose anime: 1 - 0
c_o [1-0] >

$ 1

$ Traceback (most recent call last):
  File "/usr/local/bin/anicli-ru", line 166, in <module>
    Menu.run()
  File "/usr/local/bin/anicli-ru", line 157, in run
    cls().main()
  File "/usr/local/bin/anicli-ru", line 152, in main
    if not self.command_wrapper(command):
  File "/usr/local/bin/anicli-ru", line 133, in command_wrapper
    self.__ACTIONS[command][1]()
  File "/usr/local/bin/anicli-ru", line 65, in ongoing
    self.choose_episode(int(command), ongoings)
  File "/usr/local/bin/anicli-ru", line 86, in choose_episode
    episodes = self.anime.episodes(result.choose(num))
  File "/usr/lib/python3.10/site-packages/anicli_ru-2.1.2-py3.10.egg/anicli_ru/api.py", line 382, in episodes
AttributeError: 'NoneType' object has no attribute 'id'

OS: EndeavourOS Linux x86_64
Python 3.10.1
Cloned latest commit - bd22d0260616c38fb82f586620da48b8dfb737c7

**Comment by Ziquiet** [comment]
переустановка программы и перезагрузка пк помогла

**Comment by vypivshiy** [comment]
> переустановка программы и перезагрузка пк НЕ помогла
Привет, ip адрес в какой стране находится? animego.org (сайт, с которого берутся данные) не на все страны работает, например, на американские айпишники точно.

**Comment by Ziquiet** [comment]
Ip находится в Украине. сайт работал, но поиск в скрипте не работал. Установил Debian 11, все работает, проблема решилась.
