### ISSUE TITLE
Не могу установить

### ISSUE THREAD

**Issue by user357** [vypivshiy/ani-cli-ru#24]
Система Arch Linux.

[user]$ sudo python -m pip install anicli-ru
Collecting anicli-ru
  Using cached anicli-ru-4.2.3.tar.gz (36 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dwyu__vq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dwyu__vq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dwyu__vq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dwyu__vq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/tmp/pip-install-lly02wb_/anicli-ru_6368b0d51a9546a1beef55bc726727f6/anicli_ru/__init__.py", line 1, in <module>
          from anicli_ru.kodik import Kodik
        File "/tmp/pip-install-lly02wb_/anicli-ru_6368b0d51a9546a1beef55bc726727f6/anicli_ru/kodik.py", line 8, in <module>
          from anicli_ru._http import client
        File "/tmp/pip-install-lly02wb_/anicli-ru_6368b0d51a9546a1beef55bc726727f6/anicli_ru/_http.py", line 4, in <module>
          from requests import Session, Response
      ModuleNotFoundError: No module named 'requests'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[user]$ sudo pip install requests

Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (2.28.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests) (1.26.16)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by user357** [comment]
Решается установкой 
sudo pip install wheel setuptools pip --upgrade
sudo pip3 install wheel setuptools pip --upgrade

Использоваться sudo если для всех, и это не безопасно

**Comment by user357** [comment]
Выше
