### ISSUE TITLE
[4.2.6] animania not working

### ISSUE THREAD

**Issue by rumly111** [vypivshiy/ani-cli-ru#27]
I use stable version from PIP (4.2.6), searching anime works, but when I try to play from `animania` source, I get traceback:

```
 Traceback (most recent call last):
  File "/home/joseph/.local/bin/anicli-ru", line 8, in <module>
    sys.exit(main())
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 271, in main
    Menu.run()
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 247, in run
    cls().main()
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 173, in main
    if not self.command_wrapper(command):
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 67, in command_wrapper
    self.__ACTIONS[command][1]()
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 79, in ongoing
    self.choose_episode(ongoings[int(command) - 1])
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 114, in choose_episode
    self.choose_dub(results)
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 97, in choose_dub
    self._run_video(results[command - 1])
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/anicli.py", line 181, in _run_video
    url = player.get_video(quality=args.QUALITY)
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/base.py", line 341, in get_video
    return a.get_video(player_url=self.url, quality=quality, referer=referer)
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/base.py", line 222, in get_video
    url = self.get_kodik_video(player_url, quality, referer=referer)
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/base.py", line 196, in get_kodik_video
    return Kodik()(player_url, quality, referer=referer)
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/kodik.py", line 122, in __call__
    return self.parse(player_url, quality=quality, referer=referer)
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/kodik.py", line 111, in parse
    video_url = cls()._get_kodik_video_links(api_url, new_referer, data)["360"][0]["src"]  # type: ignore
  File "/home/joseph/.local/lib/python3.10/site-packages/anicli_ru/kodik.py", line 156, in _get_kodik_video_links
    "accept": "application/json, text/javascript, */*; q=0.01"}).json()["links"]
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by 1myProject** [comment]
This is Kodik's problem. It changed the entry point from "vdu" to "ftor".

**Comment by vypivshiy** [comment]
Hi!

I'm lazily developing the dev version of CLI client and forgot to add a patch to the master 😭

Shortly, kodik regularly updates the path [example extract implementation](https://github.com/vypivshiy/anicli-api/blob/master/anicli_api/player/kodik.py#L96) to the base64 encoded API entrypoint (plz, do not ask wtf, i dont know 😂) and therefore you need to make an additional request to the js player to get the correct path.

**Comment by rumly111** [comment]
thanks!
