### ISSUE TITLE
Не работает aniboom.one ни у одного аниме

### ISSUE THREAD

**Issue by ILYFKA** [vypivshiy/ani-cli-ru#29]
```
~/search/episode/video 1
Traceback (most recent call last):
  File "/home/code_wizard/.local/bin/anicli-ru", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli/__init__.py", line 72, in run_cli
    APP.loop()
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/app.py", line 236, in loop
    self._handle_commands()
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/app.py", line 305, in _handle_commands
    self._handle_error(key, args, exc)
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/app.py", line 253, in _handle_error
    raise exc
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/app.py", line 294, in _handle_commands
    if result := self.command_manager.exec(key, args):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/manager.py", line 91, in exec
    raise e
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/manager.py", line 75, in exec
    return command.handle(args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/command/objects.py", line 24, in handle
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 42, in search
    app.fsm.run(SearchStates)
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 145, in run
    return self._current_fsm.run(state.first())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 59, in run
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 60, in start_search
    app.fsm.next()
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 155, in next
    self._current_fsm.next()
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 73, in next
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 95, in choose_episode
    app.fsm.set(SearchStates.SOURCE)
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 160, in set
    self._current_fsm.set(state)
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 52, in set
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 116, in choose_source
    app.fsm.set(SearchStates.VIDEO)
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 160, in set
    self._current_fsm.set(state)
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 52, in set
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 122, in choose_quality
    videos = source.get_videos(**app.CFG.httpx_kwargs())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli_api/base.py", line 159, in get_videos
    return extractor(**httpx_kwargs).parse(self.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli_api/player/base.py", line 23, in wrapper
    return func(_, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli_api/player/aniboom.py", line 27, in parse
    return self._extract(response)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/code_wizard/.local/lib/python3.11/site-packages/anicli_api/player/aniboom.py", line 46, in _extract
    url=dash.re(r"https:.*\.mpd")[0].replace("\\", ""),
        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by vypivshiy** [comment]
Привет! 

Это баг шреденгира со стороны aniboom: то он отваливается, то работает

фикс будет на этой неделе

**Comment by vypivshiy** [comment]
залил фикс на pypi, надо обновить api модуль
pipx:

```
pipx runpip anicli-ru install anicli-api -U
```

pip:
```
pip install anicli-api -U
```
