### ISSUE TITLE
doesnt works animego 

### ISSUE THREAD

**Issue by azikx-linuxuser** [vypivshiy/ani-cli-ru#30]
```
Traceback (most recent call last):
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/manager.py", line 76, in exec
    return command.handle(args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/command/objects.py", line 24, in handle
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 42, in search
    app.fsm.run(SearchStates)
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 145, in run
    return self._current_fsm.run(state.first())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 59, in run
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 60, in start_search
    app.fsm.next()
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 155, in next
    self._current_fsm.next()
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 73, in next
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 95, in choose_episode
    app.fsm.set(SearchStates.SOURCE)
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 160, in set
    self._current_fsm.set(state)
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 52, in set
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 116, in choose_source
    app.fsm.set(SearchStates.VIDEO)
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 160, in set
    self._current_fsm.set(state)
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 52, in set
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli/cli/search.py", line 122, in choose_quality
    videos = source.get_videos(**app.CFG.httpx_kwargs())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli_api/base.py", line 206, in get_videos
    return extractor(**httpx_kwargs).parse(self.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli_api/player/base.py", line 28, in wrapper
    return func(cls, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/anicli_api/player/kodik.py", line 165, in parse
    return self._extract(response_api.json()["links"])
                         ^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/app.py", line 255, in _handle_error
    raise exc
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/app.py", line 298, in _handle_commands
    if result := self.command_manager.exec(key, args):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/lib/python3.11/site-packages/eggella/manager.py", line 89, in exec
    raise CommandRuntimeError(msg) from e
eggella.exceptions.CommandRuntimeError: JSONDecodeError('Expecting value: line 1 column 1 (char 0)') in `search` callable
```

![20240404_18h46m17s_grim](https://github.com/vypivshiy/ani-cli-ru/assets/55180817/8002e4f0-9a7f-4e4a-888b-a4183e13ce21)

**Comment by vypivshiy** [comment]
Привет! animego работает, это проблема с kodik плеером.
Примерно неделю назад они серверную часть обновили, а я патч залил.

Для устарнения проблемы необходимо обновить библиотеку [anicli-api](https://github.com/vypivshiy/anicli-api) до версии 0.6.4:

Если клиент установлен через pip:

```shell
pip install anicli-api --upgrade
```

Если клиент установлен через pipx:

```shell
pipx runpip anicli-ru install anicli-api --upgrade
```

Также, если локация IP адреса клиента отличается от СНГ, то kodik не будет работать.

**Comment by azikx-linuxuser** [comment]
Хорошо, спасибо ❤️
