### ISSUE TITLE
error when i want search title

### ISSUE THREAD

**Issue by azikx-linuxuser** [vypivshiy/ani-cli-ru#31]
```
Press |CTRL+C| or |CTRL+D| or type exit for close this app
Press |TAB| or type help for get commands information
Loaded source provider: animego.org
> search Рубеж Шангри Ла
Error! command `search` with args: Рубеж Шангри Ла
Full traceback:
Traceback (most recent call last):
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/anicli_api/_http.py", line 87, in handle_request
    resp = super().handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/manager.py", line 76, in exec
    return command.handle(args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/command/objects.py", line 24, in handle
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/anicli/cli/search.py", line 42, in search
    app.fsm.run(SearchStates)
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 145, in run
    return self._current_fsm.run(state.first())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 59, in run
    return self._exec_state(self._current_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/fsm/fsm.py", line 48, in _exec_state
    return self.handlers[state]()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/anicli/cli/search.py", line 48, in start_search
    results = app.CFG.EXTRACTOR.search(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/anicli_api/source/animego.py", line 47, in search
    resp = self.http.get(f"{self.BASE_URL}/search/anime", params={"q": query})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_client.py", line 1041, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/anicli_api/_http.py", line 99, in handle_request
    "[%s] %s: %s, %s -> %s try again", i + 1, exc_name, exc_msg, repr(request), repr(resp)
                                                                                     ^^^^
UnboundLocalError: cannot access local variable 'resp' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/app.py", line 255, in _handle_error
    raise exc
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/app.py", line 298, in _handle_commands
    if result := self.command_manager.exec(key, args):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azik/.local/share/pipx/venvs/anicli-ru/lib/python3.11/site-packages/eggella/manager.py", line 100, in exec
    raise CommandRuntimeError(msg)
eggella.exceptions.CommandRuntimeError: UnboundLocalError("cannot access local variable 'resp' where it is not associated with a value") in `search` callable
```

По проверкам не работает даже сайт

**Comment by azikx-linuxuser** [comment]
Все, заработало, видимо ошибка была именно в сайте, он временно был недоступен как я понял

**Comment by azikx-linuxuser** [comment]
Снова не работает, видимо проблема не только в сайте но и в провайдере так как мой айпи попадает под СНГ, но у других провайдеров таких как МТС мобильного интернета все работает, мой же ТСТ

**Comment by azikx-linuxuser** [comment]
Заработало после сброса роутера
