### ISSUE TITLE
Not working Ubuntu 20.04

### ISSUE THREAD

**Issue by yaroslavyakovkin** [vypivshiy/ani-cli-ru#32]
Привет, для начала спасибо за этот проект. Протестировал твое приложение на Lubuntu 22, заработало прекрасно. Решил попробовать на Ubuntu 20.04, выдает следующую ошибку при запуске:

```
Traceback (most recent call last):
  File "/home/yrk/.local/bin/anicli-ru", line 5, in <module>
    from anicli import run_cli
  File "/home/yrk/.local/pipx/venvs/anicli-ru/lib/python3.8/site-packages/anicli/__init__.py", line 6, in <module>
    from anicli.cli import APP
  File "/home/yrk/.local/pipx/venvs/anicli-ru/lib/python3.8/site-packages/anicli/cli/__init__.py", line 1, in <module>
    from anicli.cli import events, ongoing, search
  File "/home/yrk/.local/pipx/venvs/anicli-ru/lib/python3.8/site-packages/anicli/cli/ongoing.py", line 10, in <module>
    from anicli.cli.player import run_video
  File "/home/yrk/.local/pipx/venvs/anicli-ru/lib/python3.8/site-packages/anicli/cli/player.py", line 44, in <module>
    class MpvPlayer(BasePlayer):
  File "/home/yrk/.local/pipx/venvs/anicli-ru/lib/python3.8/site-packages/anicli/cli/player.py", line 70, in MpvPlayer
    def _parse_headers_args(cls, headers: dict[str, Any]):
TypeError: 'type' object is not subscriptable
```

**Comment by vypivshiy** [comment]
Привет, это мой косяк, что сделал метку поддержки python3.8 и случайно аннотировал типом неподдерживаемым этой версией. Фикс залью, но по возможности лучше хотябы на 3.9 и выше обновить python ([официально прекратят поддерживать в октябре 2024 года](https://peps.python.org/pep-0569/#source-only-security-fix-releases))
